# Generated by Django 2.0.6 on 2018-06-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('projector', models.BooleanField(verbose_name='projector')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_reservations.Room', verbose_name='room_id'),
        ),
    ]
