# Generated by Django 2.0.6 on 2018-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservations', '0002_auto_20180609_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
